version: '3.7'

services:
   java-dev:
      container_name: java-dev
      hostname: java-dev.local
      build:
         context: .
      working_dir: /src
      volumes:
         - ..:/src:cached
      command: >
         bash -c "sleep infinity"
      networks:
         macroactive:

networks:
   macroactive:
